# Generated by Django 3.2.9 on 2021-12-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masuk', models.DateTimeField(blank=True, verbose_name='Masuk')),
                ('keluar', models.DateTimeField(blank=True, verbose_name='Keluar')),
            ],
        ),
    ]
