# Generated by Django 3.2.9 on 2021-12-08 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role_divisi', '0001_initial'),
        ('autentikasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='divisi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='role_divisi.roledivisi'),
        ),
    ]
