# Generated by Django 3.2.9 on 2021-12-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Izin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('staf', models.CharField(max_length=20)),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField()),
            ],
        ),
    ]
