# Generated by Django 3.2.9 on 2021-12-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Izin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staf', models.CharField(max_length=20)),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=10)),
            ],
        ),
    ]
