# Generated by Django 3.2.9 on 2021-12-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perizinan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='izin',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
