# Generated by Django 3.2.9 on 2021-12-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perizinan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
