# Generated by Django 3.2.9 on 2021-12-08 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perizinan', '0002_alter_izin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izin',
            name='staf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='izin',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak')], default='PENDING', max_length=10),
        ),
    ]
