# Generated by Django 3.2.9 on 2021-12-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perizinan', '0003_auto_20211208_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izin',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('ST', 'Disetujui'), ('TL', 'Ditolak')], default='PD', max_length=10),
        ),
    ]
